version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: people-house-app:latest
    container_name: people-house-app
    restart: unless-stopped
    ports:
      - 80:80
